language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install -e .
script:
  - coverage run --source pyDenStream/tests/ -m pytest
after_success:
  - codecov