[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "denstream"
version = "0.1.4"
description = "Implementation of the DenStream algorithm"
readme = "README.md"
requires-python = ">=3.10, <3.15"
authors = [
    {name = "MrParosk"}
]

dependencies = [
    "numba>=0.60",
    "numpy>=2.1",
    "scikit-learn>=1.4",
    "typing-extensions>=4.15.0",
]


[dependency-groups]
dev = [
    "mypy>=1.18.2",
    "pre-commit>=4.5.0",
    "pytest>=9.0.1",
    "pytest-cov>=7.0.0",
    "ruff>=0.14.6",
]

[tool.mypy]
ignore_missing_imports = true
strict = true
exclude = [
    "build",
    "tests"
]

[tool.ruff]
line-length = 128
