[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=61.0", "wheel>=0.37.1"]

[project]
name = "denstream"
version = "0.1"
description = "Implementation of the DenStream algorithm"
requires-python = ">=3.8, <3.13"
authors = [
    {name = "MrParosk"}
]

dependencies = [
    "numba>=0.56.2",
    "numpy>=1.23",
    "scikit-learn>=1.0",
]

[project.optional-dependencies]
dev = [
    "black==24.2.0",
    "isort==5.13.2",
    "mypy==1.8.0",
    "pre-commit==3.6.2",
    "pytest==8.0.2",
    "pytest-cov==4.1.0",
    "ruff==0.3.0"
]

[tool.mypy]
ignore_missing_imports = true
exclude = "build"

[tool.black]
line-length = 128

[tool.isort]
line_length = 128
profile = "black"

[tool.ruff]
line-length = 128
